name: 💡 Feature request
description: Suggest a new idea or improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: feature
    attributes:
      label: What problem does this solve?
      description: A clear and concise description of the problem.
      placeholder: "I often find myself..."
      validations:
        required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you looked at other approaches?
